name:                pointed-validation
version:             0.1.0.0
github:              "graninas/pointed-validation"
license:             BSD3
author:              "Alexander Granin"
maintainer:          "graninas@gmail.com"
copyright:           "2019 Alexander Granin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/graninas/pointed-validation#readme>

dependencies:
- base >= 4.7 && < 5
- validation
- lens
- template-haskell
- text

library:
  source-dirs: src

tests:
  pointed-validation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pointed-validation
    - hspec
